const
  WIDTH* = 500
  HEIGHT* = 500

  H_WIDTH* = WIDTH / 2
  H_HEIGHT* = HEIGHT / 2

  NUM_SQUARES* = 3
  SQUARE_WIDTH* = WIDTH/NUM_SQUARES - 30
  SQUARE_SPACE* = SQUARE_WIDTH #still not figured out