const
  WIDTH* = 500
  HEIGHT* = 500

  H_WIDTH* = WIDTH / 2
  H_HEIGHT* = HEIGHT / 2

<<<<<<< HEAD
  NUM_SQUARES* = 3
  SQUARE_WIDTH* = WIDTH/NUM_SQUARES - 30
  SQUARE_SPACE* = SQUARE_WIDTH #still not figured out
=======
  NUM_SQUARES* = 5
  SQUARE_SIZE* = WIDTH / NUM_SQUARES
  MARGIN_RATIO = 0.05
  SQUARE_MARGIN* = int(SQUARE_SIZE * MARGIN_RATIO)
  SQUARE_BODY* = SQUARE_SIZE - (SQUARE_MARGIN * 2)
>>>>>>> eea171145debeacd6573c07647edea9998fc7cf8
